runtime: nodejs18   # 使用する Node.js のバージョン
env: standard       # 環境を標準環境に設定
service: ai-education-dinosor-dash

handlers:
  # すべての URL を index.html にルーティング
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # dist ディレクトリ内の静的ファイルを提供
  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)

# 自動スケーリングの設定
automatic_scaling:
  min_idle_instances: automatic  # 最小アイドルインスタンス数
  max_idle_instances: automatic  # 最大アイドルインスタンス数
  min_pending_latency: automatic # 最小待機遅延
  max_pending_latency: automatic # 最大待機遅延