import { mobileTabletCheck } from './utils.js'

const IS_MOBILE = mobileTabletCheck();

export default {
    DEFAULT_MODEL: "quickdraw-mobilevit-small",
    DEFAULT_QUANTIZED: false,
    BANNED_LABELS: [
        // List of banned labels, because they are either:
        // - Too similar to other labels
        // - Too difficult to draw
        // - Too difficult to understand
        // - Ambiguous
        "動物の移動", // 理解が難しいため
        "腕", // "肘"と似すぎているため
        "納屋", // 他の建物の種類と似すぎているため
        "コウモリ", // 動物とスポーツ用具のどちらか曖昧なため
        "脳", // 描くのが難しいため
        "コーヒーカップ", // "マグカップ"と似すぎているため
        "円", // 縮小した時に常に八角形として検出されるため
        "六角形", // "八角形"と似すぎているため
        "縫い目", // "雷"や"ジグザグ"と似すぎているため
        "セーター", // "ジャケット"と似すぎているため
        "バン", // 他の種類の乗り物と似すぎているため
    ],
    BANNED_EN_LABELS: [
        // List of banned labels, because they are either:
        // - Too similar to other labels
        // - Too difficult to draw
        // - Too difficult to understand
        // - Ambiguous
        "animal migration", // too difficult to understand
        "arm", // too similar to "elbow"
        "barn", // too similar to other types of buildings
        "bat", // ambiguous (animal vs. sports equipment)
        "brain", // too difficult to draw
        "coffee cup", // too similar to mug
        "circle", // when scaled down, always detected as an octogon
        "hexagon", // too similar to octogon
        "stitches", // too similar to lightning/zigzag
        "sweather", // too similar to "jacket"
        "van", // too similar to other types of vehicles
    ],    
    PREDICTION_REFRESH_TIME: 10,
    BRUSH_SIZE: IS_MOBILE ? 12 : 16,
    TARGET_FPS: 60,
    GAME_DURATION: 60 + 0.5, // + 0.5 so it doesn't flicker (TODO: change to 60)
    COUNTDOWN_TIMER: 3,

    START_REJECT_THRESHOLD: 0.2, // How confident the model should be before starting to reject
    REJECT_TIME_DELAY: 3 * 1000, // How many ms to wait before helping
    REJECT_TIME_PER_LABEL: 3 * 1000, // How many ms to reject a label for after it's been drawn

    SKIP_PENALTY: 3 * 1000, // How much to penalize for skipping a drawing
    
    LABELS: {
        "0": "航空母艦",
        "1": "飛行機",
        "2": "目覚まし時計",
        "3": "救急車",
        "4": "天使",
        "5": "動物の移動",
        "6": "アリ",
        "7": "金床",
        "8": "リンゴ",
        "9": "腕",
        "10": "アスパラガス",
        "11": "斧",
        "12": "バックパック",
        "13": "バナナ",
        "14": "包帯",
        "15": "納屋",
        "16": "野球のバット",
        "17": "野球",
        "18": "バスケット",
        "19": "バスケットボール",
        "20": "コウモリ",
        "21": "浴槽",
        "22": "ビーチ",
        "23": "熊",
        "24": "ひげ",
        "25": "ベッド",
        "26": "ミツバチ",
        "27": "ベルト",
        "28": "ベンチ",
        "29": "自転車",
        "30": "双眼鏡",
        "31": "鳥",
        "32": "誕生日のケーキ",
        "33": "ブラックベリー",
        "34": "ブルーベリー",
        "35": "本",
        "36": "ブーメラン",
        "37": "ボトルキャップ",
        "38": "蝶ネクタイ",
        "39": "ブレスレット",
        "40": "脳",
        "41": "パン",
        "42": "橋",
        "43": "ブロッコリー",
        "44": "ほうき",
        "45": "バケツ",
        "46": "ブルドーザー",
        "47": "バス",
        "48": "低木",
        "49": "蝶",
        "50": "サボテン",
        "51": "ケーキ",
        "52": "電卓",
        "53": "カレンダー",
        "54": "ラクダ",
        "55": "カメラ",
        "56": "迷彩",
        "57": "キャンプファイヤー",
        "58": "ろうそく",
        "59": "大砲",
        "60": "カヌー",
        "61": "自動車",
        "62": "ニンジン",
        "63": "城",
        "64": "猫",
        "65": "天井ファン",
        "66": "携帯電話",
        "67": "チェロ",
        "68": "椅子",
        "69": "シャンデリア",
        "70": "教会",
        "71": "円",
        "72": "クラリネット",
        "73": "時計",
        "74": "雲",
        "75": "コーヒーカップ",
        "76": "コンパス",
        "77": "コンピューター",
        "78": "クッキー",
        "79": "クーラー",
        "80": "ソファ",
        "81": "牛",
        "82": "カニ",
        "83": "クレヨン",
        "84": "ワニ",
        "85": "王冠",
        "86": "クルーズ船",
        "87": "カップ",
        "88": "ダイヤモンド",
        "89": "食器洗い機",
        "90": "飛び込み板",
        "91": "犬",
        "92": "イルカ",
        "93": "ドーナツ",
        "94": "ドア",
        "95": "ドラゴン",
        "96": "ドレッサー",
        "97": "ドリル",
        "98": "ドラム",
        "99": "アヒル",
        "100": "ダンベル",
        "101": "耳",
        "102": "肘",
        "103": "象",
        "104": "封筒",
        "105": "消しゴム",
        "106": "目",
        "107": "眼鏡",
        "108": "顔",
        "109": "扇風機",
        "110": "羽",
        "111": "フェンス",
        "112": "指",
        "113": "消火栓",
        "114": "暖炉",
        "115": "消防車",
        "116": "魚",
        "117": "フラミンゴ",
        "118": "懐中電灯",
        "119": "ビーチサンダル",
        "120": "フロアランプ",
        "121": "花",
        "122": "空飛ぶ円盤",
        "123": "足",
        "124": "フォーク",
        "125": "カエル",
        "126": "フライパン",
        "127": "ガーデンホース",
        "128": "庭",
        "129": "キリン",
        "130": "ゴーティー",
        "131": "ゴルフクラブ",
        "132": "ブドウ",
        "133": "草",
        "134": "ギター",
        "135": "ハンバーガー",
        "136": "ハンマー",
        "137": "手",
        "138": "ハープ",
        "139": "帽子",
        "140": "ヘッドホン",
        "141": "ハリネズミ",
        "142": "ヘリコプター",
        "143": "ヘルメット",
        "144": "六角形",
        "145": "ホッケーパック",
        "146": "ホッケースティック",
        "147": "馬",
        "148": "病院",
        "149": "熱気球",
        "150": "ホットドッグ",
        "151": "ホットタブ",
        "152": "砂時計",
        "153": "観葉植物",
        "154": "家",
        "155": "ハリケーン",
        "156": "アイスクリーム",
        "157": "ジャケット",
        "158": "刑務所",
        "159": "カンガルー",
        "160": "鍵",
        "161": "キーボード",
        "162": "膝",
        "163": "ナイフ",
        "164": "はしご",
        "165": "ランタン",
        "166": "ラップトップ",
        "167": "葉",
        "168": "脚",
        "169": "電球",
        "170": "ライター",
        "171": "灯台",
        "172": "雷",
        "173": "線",
        "174": "ライオン",
        "175": "口紅",
        "176": "ロブスター",
        "177": "ロリポップ",
        "178": "郵便受け",
        "179": "地図",
        "180": "マーカー",
        "181": "マッチ",
        "182": "メガホン",
        "183": "人魚",
        "184": "マイクロフォン",
        "185": "電子レンジ",
        "186": "猿",
        "187": "月",
        "188": "蚊",
        "189": "オートバイ",
        "190": "山",
        "191": "マウス",
        "192": "口髭",
        "193": "口",
        "194": "マグカップ",
        "195": "キノコ",
        "196": "釘",
        "197": "ネックレス",
        "198": "鼻",
        "199": "海",
        "200": "八角形",
        "201": "タコ",
        "202": "玉ねぎ",
        "203": "オーブン",
        "204": "フクロウ",
        "205": "塗料缶",
        "206": "絵筆",
        "207": "ヤシの木",
        "208": "パンダ",
        "209": "ズボン",
        "210": "ペーパークリップ",
        "211": "パラシュート",
        "212": "オウム",
        "213": "パスポート",
        "214": "ピーナッツ",
        "215": "ナシ",
        "216": "エンドウ",
        "217": "鉛筆",
        "218": "ペンギン",
        "219": "ピアノ",
        "220": "ピックアップトラック",
        "221": "写真立て",
        "222": "豚",
        "223": "枕",
        "224": "パイナップル",
        "225": "ピザ",
        "226": "ペンチ",
        "227": "パトカー",
        "228": "池",
        "229": "プール",
        "230": "アイスキャンディー",
        "231": "ポストカード",
        "232": "ジャガイモ",
        "233": "電源コンセント",
        "234": "財布",
        "235": "ウサギ",
        "236": "アライグマ",
        "237": "ラジオ",
        "238": "雨",
        "239": "虹",
        "240": "レーキ（熊手）",
        "241": "リモコン",
        "242": "サイ",
        "243": "ライフル",
        "244": "川",
        "245": "ジェットコースター",
        "246": "ローラースケート",
        "247": "帆船",
        "248": "サンドイッチ",
        "249": "のこぎり",
        "250": "サックス",
        "251": "スクールバス",
        "252": "はさみ",
        "253": "サソリ",
        "254": "ドライバー",
        "255": "ウミガメ",
        "256": "シーソー",
        "257": "サメ",
        "258": "羊",
        "259": "靴",
        "260": "ショートパンツ",
        "261": "シャベル",
        "262": "シンク",
        "263": "スケートボード",
        "264": "頭蓋骨",
        "265": "摩天楼",
        "266": "寝袋",
        "267": "スマイリーフェイス",
        "268": "カタツムリ",
        "269": "ヘビ",
        "270": "シュノーケル",
        "271": "雪の結晶",
        "272": "雪だるま",
        "273": "サッカーボール",
        "274": "靴下",
        "275": "スピードボート",
        "276": "クモ",
        "277": "スプーン",
        "278": "スプレッドシート",
        "279": "正方形",
        "280": "スクイグル",
        "281": "リス",
        "282": "階段",
        "283": "星",
        "284": "ステーキ",
        "285": "ステレオ",
        "286": "聴診器",
        "287": "縫い目",
        "288": "一時停止標識",
        "289": "ストーブ",
        "290": "イチゴ",
        "291": "街灯",
        "292": "インゲン",
        "293": "潜水艦",
        "294": "スーツケース",
        "295": "太陽",
        "296": "白鳥",
        "297": "セーター",
        "298": "ブランコ",
        "299": "剣",
        "300": "注射器",
        "301": "Tシャツ",
        "302": "テーブル",
        "303": "ティーポット",
        "304": "テディベア",
        "305": "電話",
        "306": "テレビ",
        "307": "テニスラケット",
        "308": "テント",
        "309": "エッフェル塔",
        "310": "万里の長城",
        "311": "モナリザ",
        "312": "虎",
        "313": "トースター",
        "314": "つま先",
        "315": "トイレ",
        "316": "歯",
        "317": "歯ブラシ",
        "318": "歯磨き粉",
        "319": "竜巻",
        "320": "トラクター",
        "321": "信号機",
        "322": "列車",
        "323": "木",
        "324": "三角形",
        "325": "トロンボーン",
        "326": "トラック",
        "327": "トランペット",
        "328": "傘",
        "329": "下着",
        "330": "バン",
        "331": "花瓶",
        "332": "バイオリン",
        "333": "洗濯機",
        "334": "スイカ",
        "335": "ウォータースライド",
        "336": "鯨",
        "337": "車輪",
        "338": "風車",
        "339": "ワインボトル",
        "340": "ワイングラス",
        "341": "腕時計",
        "342": "ヨガ",
        "343": "シマウマ",
        "344": "ジグザグ"   
    },
    EN_TO_JA_LABELS: {
        "aircraft carrier": "航空母艦",
        "airplane": "飛行機",
        "alarm clock": "目覚まし時計",
        "ambulance": "救急車",
        "angel": "天使",
        "animal migration": "動物の移動",
        "ant": "アリ",
        "anvil": "金床",
        "apple": "リンゴ",
        "arm": "腕",
        "asparagus": "アスパラガス",
        "axe": "斧",
        "backpack": "バックパック",
        "banana": "バナナ",
        "bandage": "包帯",
        "barn": "納屋",
        "baseball bat": "野球のバット",
        "baseball": "野球",
        "basket": "バスケット",
        "basketball": "バスケットボール",
        "bat": "コウモリ",
        "bathtub": "浴槽",
        "beach": "ビーチ",
        "bear": "熊",
        "beard": "ひげ",
        "bed": "ベッド",
        "bee": "ミツバチ",
        "belt": "ベルト",
        "bench": "ベンチ",
        "bicycle": "自転車",
        "binoculars": "双眼鏡",
        "bird": "鳥",
        "birthday cake": "誕生日のケーキ",
        "blackberry": "ブラックベリー",
        "blueberry": "ブルーベリー",
        "book": "本",
        "boomerang": "ブーメラン",
        "bottlecap": "ボトルキャップ",
        "bowtie": "蝶ネクタイ",
        "bracelet": "ブレスレット",
        "brain": "脳",
        "bread": "パン",
        "bridge": "橋",
        "broccoli": "ブロッコリー",
        "broom": "ほうき",
        "bucket": "バケツ",
        "bulldozer": "ブルドーザー",
        "bus": "バス",
        "bush": "低木",
        "butterfly": "蝶",
        "cactus": "サボテン",
        "cake": "ケーキ",
        "calculator": "電卓",
        "calendar": "カレンダー",
        "camel": "ラクダ",
        "camera": "カメラ",
        "camouflage": "迷彩",
        "campfire": "キャンプファイヤー",
        "candle": "ろうそく",
        "cannon": "大砲",
        "canoe": "カヌー",
        "car": "自動車",
        "carrot": "ニンジン",
        "castle": "城",
        "cat": "猫",
        "ceiling fan": "天井ファン",
        "cell phone": "携帯電話",
        "cello": "チェロ",
        "chair": "椅子",
        "chandelier": "シャンデリア",
        "church": "教会",
        "circle": "円",
        "clarinet": "クラリネット",
        "clock": "時計",
        "cloud": "雲",
        "coffee cup": "コーヒーカップ",
        "compass": "コンパス",
        "computer": "コンピューター",
        "cookie": "クッキー",
        "cooler": "クーラー",
        "couch": "ソファ",
        "cow": "牛",
        "crab": "カニ",
        "crayon": "クレヨン",
        "crocodile": "ワニ",
        "crown": "王冠",
        "cruise ship": "クルーズ船",
        "cup": "カップ",
        "diamond": "ダイヤモンド",
        "dishwasher": "食器洗い機",
        "diving board": "飛び込み板",
        "dog": "犬",
        "dolphin": "イルカ",
        "donut": "ドーナツ",
        "door": "ドア",
        "dragon": "ドラゴン",
        "dresser": "ドレッサー",
        "drill": "ドリル",
        "drums": "ドラム",
        "duck": "アヒル",
        "dumbbell": "ダンベル",
        "ear": "耳",
        "elbow": "肘",
        "elephant": "象",
        "envelope": "封筒",
        "eraser": "消しゴム",
        "eye": "目",
        "eyeglasses": "眼鏡",
        "face": "顔",
        "fan": "扇風機",
        "feather": "羽",
        "fence": "フェンス",
        "finger": "指",
        "fire hydrant": "消火栓",
        "fireplace": "暖炉",
        "firetruck": "消防車",
        "fish": "魚",
        "flamingo": "フラミンゴ",
        "flashlight": "懐中電灯",
        "flip flops": "ビーチサンダル",
        "floor lamp": "フロアランプ",
        "flower": "花",
        "flying saucer": "空飛ぶ円盤",
        "foot": "足",
        "fork": "フォーク",
        "frog": "カエル",
        "frying pan": "フライパン",
        "garden hose": "ガーデンホース",
        "garden": "庭",
        "giraffe": "キリン",
        "goatee": "ゴーティー",
        "golf club": "ゴルフクラブ",
        "grapes": "ブドウ",
        "grass": "草",
        "guitar": "ギター",
        "hamburger": "ハンバーガー",
        "hammer": "ハンマー",
        "hand": "手",
        "harp": "ハープ",
        "hat": "帽子",
        "headphones": "ヘッドホン",
        "hedgehog": "ハリネズミ",
        "helicopter": "ヘリコプター",
        "helmet": "ヘルメット",
        "hexagon": "六角形",
        "hockey puck": "ホッケーパック",
        "hockey stick": "ホッケースティック",
        "horse": "馬",
        "hospital": "病院",
        "hot air balloon": "熱気球",
        "hot dog": "ホットドッグ",
        "hot tub": "ホットタブ",
        "hourglass": "砂時計",
        "house plant": "観葉植物",
        "house": "家",
        "hurricane": "ハリケーン",
        "ice cream": "アイスクリーム",
        "jacket": "ジャケット",
        "jail": "刑務所",
        "kangaroo": "カンガルー",
        "key": "鍵",
        "keyboard": "キーボード",
        "knee": "膝",
        "knife": "ナイフ",
        "ladder": "はしご",
        "lantern": "ランタン",
        "laptop": "ラップトップ",
        "leaf": "葉",
        "leg": "脚",
        "light bulb": "電球",
        "lighter": "ライター",
        "lighthouse": "灯台",
        "lightning": "雷",
        "line": "線",
        "lion": "ライオン",
        "lipstick": "口紅",    
        "lobster": "ロブスター",
        "lollipop": "ロリポップ",
        "mailbox": "郵便受け",
        "map": "地図",
        "marker": "マーカー",
        "matches": "マッチ",
        "megaphone": "メガホン",
        "mermaid": "人魚",
        "microphone": "マイクロフォン",
        "microwave": "電子レンジ",
        "monkey": "猿",
        "moon": "月",
        "mosquito": "蚊",
        "motorbike": "オートバイ",
        "mountain": "山",
        "mouse": "マウス",
        "moustache": "口髭",
        "mouth": "口",
        "mug": "マグカップ",
        "mushroom": "キノコ",
        "nail": "釘",
        "necklace": "ネックレス",
        "nose": "鼻",
        "ocean": "海",
        "octagon": "八角形",
        "octopus": "タコ",
        "onion": "玉ねぎ",
        "oven": "オーブン",
        "owl": "フクロウ",
        "paint can": "塗料缶",
        "paintbrush": "絵筆",
        "palm tree": "ヤシの木",
        "panda": "パンダ",
        "pants": "ズボン",
        "paper clip": "ペーパークリップ",
        "parachute": "パラシュート",
        "parrot": "オウム",
        "passport": "パスポート",
        "peanut": "ピーナッツ",
        "pear": "ナシ",
        "peas": "エンドウ",
        "pencil": "鉛筆",
        "penguin": "ペンギン",
        "piano": "ピアノ",
        "pickup truck": "ピックアップトラック",
        "picture frame": "写真立て",
        "pig": "豚",
        "pillow": "枕",
        "pineapple": "パイナップル",
        "pizza": "ピザ",
        "pliers": "ペンチ",
        "police car": "パトカー",
        "pond": "池",
        "pool": "プール",
        "popsicle": "アイスキャンディー",
        "postcard": "ポストカード",
        "potato": "ジャガイモ",
        "power outlet": "電源コンセント",
        "purse": "財布",
        "rabbit": "ウサギ",
        "raccoon": "アライグマ",
        "radio": "ラジオ",
        "rain": "雨",
        "rainbow": "虹",
        "rake": "レーキ（熊手）",
        "remote control": "リモコン",
        "rhinoceros": "サイ",
        "rifle": "ライフル",
        "river": "川",
        "roller coaster": "ジェットコースター",
        "rollerskates": "ローラースケート",
        "sailboat": "帆船",
        "sandwich": "サンドイッチ",
        "saw": "のこぎり",
        "saxophone": "サックス",
        "school bus": "スクールバス",
        "scissors": "はさみ",
        "scorpion": "サソリ",
        "screwdriver": "ドライバー",
        "sea turtle": "ウミガメ",
        "see saw": "シーソー",
        "shark": "サメ",
        "sheep": "羊",
        "shoe": "靴",
        "shorts": "ショートパンツ",
        "shovel": "シャベル",
        "sink": "シンク",
        "skateboard": "スケートボード",
        "skull": "頭蓋骨",
        "skyscraper": "摩天楼",
        "sleeping bag": "寝袋",
        "smiley face": "スマイリーフェイス",
        "snail": "カタツムリ",
        "snake": "ヘビ",
        "snorkel": "シュノーケル",
        "snowflake": "雪の結晶",
        "snowman": "雪だるま",
        "soccer ball": "サッカーボール",
        "sock": "靴下",
        "speedboat": "スピードボート",
        "spider": "クモ",
        "spoon": "スプーン",
        "spreadsheet": "スプレッドシート",
        "square": "正方形",
        "squiggle": "スクイグル",
        "squirrel": "リス",
        "stairs": "階段",
        "star": "星",
        "steak": "ステーキ",
        "stereo": "ステレオ",
        "stethoscope": "聴診器",
        "stitches": "縫い目",
        "stop sign": "一時停止標識",
        "stove": "ストーブ",
        "strawberry": "イチゴ",
        "streetlight": "街灯",
        "string bean": "インゲン",
        "submarine": "潜水艦",
        "suitcase": "スーツケース",
        "sun": "太陽",
        "swan": "白鳥",
        "sweater": "セーター",
        "swing set": "ブランコ",
        "sword": "剣",
        "syringe": "注射器",
        "t-shirt": "Tシャツ",
        "table": "テーブル",
        "teapot": "ティーポット",
        "teddy-bear": "テディベア",
        "telephone": "電話",
        "television": "テレビ",
        "tennis racquet": "テニスラケット",
        "tent": "テント",
        "The Eiffel Tower": "エッフェル塔",
        "The Great Wall of China": "万里の長城",
        "The Mona Lisa": "モナリザ",
        "tiger": "虎",
        "toaster": "トースター",
        "toe": "つま先",
        "toilet": "トイレ",
        "tooth": "歯",
        "toothbrush": "歯ブラシ",
        "toothpaste": "歯磨き粉",
        "tornado": "竜巻",
        "tractor": "トラクター",
        "traffic light": "信号機",
        "train": "列車",
        "tree": "木",
        "triangle": "三角形",
        "trombone": "トロンボーン",
        "truck": "トラック",
        "trumpet": "トランペット",
        "umbrella": "傘",
        "underwear": "下着",
        "van": "バン",
        "vase": "花瓶",
        "violin": "バイオリン",
        "washing machine": "洗濯機",
        "watermelon": "スイカ",
        "waterslide": "ウォータースライド",
        "whale": "鯨",
        "wheel": "車輪",
        "windmill": "風車",
        "wine bottle": "ワインボトル",
        "wine glass": "ワイングラス",
        "wristwatch": "腕時計",
        "yoga": "ヨガ",
        "zebra": "シマウマ",
        "zigzag": "ジグザグ"
    },
};
