runtime: nodejs14 # またはサポートされている他のバージョン
env: standard

handlers:
- url: /.*
  script: auto
  secure: always
  
service: ai-education-passion-war

automatic_scaling:
  max_instances: 1

env_variables:
  NODE_ENV: "production"